### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by nielsw2** [syp2001/KerrGeoPy#4]
The code should depend on Scipy version >= 1.8.0 in order to use the elliprj function (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.elliprj.html) which was introduced in this version.

**Comment by syp2001** [comment]
Could you describe the specific issue you're having with scipy? The dependency list in setup.py already specifies scipy>=1.8, so this should be handled automatically if the package is installed with pip.

**Comment by nielsw2** [comment]
I was installing it today with pip on a mac and it did not upgrade my older version of scipy. When I ran import kerrgeopy I got an error about the ellipjr function not being defined which suggested I upgrade scipy when I looked at the documentation. The solution was to manually upgrade scipy and then everything worked.

**Comment by syp2001** [comment]
That’s interesting. I just tested this in a new environment and pip did update scipy automatically as expected, so I think this may be something specific to your local environment. For now, I’ve added a note about this to the installation instructions in case anyone else runs into the same problem. I was wondering if you happen to still have the terminal output from running pip install kerrgeopy, or if you are able to replicate the issue.
